### ISSUE TITLE
Error on nodejs 6.0

### ISSUE THREAD

**Issue by epubreader** [cmhchoi/react_keystone_website#1]
Mongoose model 'error' event fired on 'CSR' with error:
 cb is not a function TypeError: cb is not a function
    at CSR.model.find.exec (/opt/test/react_keystone_website-master/src/server/models/CSR.js:38:7)
    at /opt/test/react_keystone_website-master/node_modules/keystone/node_modules/mongoose/lib/query.js:2257:18
    at tryCatch (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Mongoose model 'error' event fired on 'Product' with error:
 cb is not a function TypeError: cb is not a function
    at Product.model.find.exec (/opt/test/react_keystone_website-master/src/server/models/Product.js:33:7)
    at /opt/test/react_keystone_website-master/node_modules/keystone/node_modules/mongoose/lib/query.js:2257:18
    at tryCatch (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Mongoose model 'error' event fired on 'Product' with error:
 cb is not a function TypeError: cb is not a function
    at Product.model.find.exec (/opt/test/react_keystone_website-master/src/server/models/Product.js:33:7)
    at /opt/test/react_keystone_website-master/node_modules/keystone/node_modules/mongoose/lib/query.js:2257:18
    at tryCatch (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/opt/test/react_keystone_website-master/node_modules/keystone/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by cmhchoi** [comment]
it still works with these 'cb not a function' errors
